name: Deploy Docusaurus site

on:
  push:
    branches:
      - main # Trigger deployment on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust based on your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Verify that the problematic file exists (for debugging)
      - name: Verify file existence
        run: |
          if [ ! -f "./docs/get-started/cardano-serialization-lib/transaction-metadata.md" ]; then
            echo "File not found: ./docs/get-started/cardano-serialization-lib/transaction-metadata.md"
            exit 1
          else
            echo "File exists: ./docs/get-started/cardano-serialization-lib/transaction-metadata.md"
          fi

      # Step 5: Build the Docusaurus project (this uses your custom build command)
      - name: Build Docusaurus site
        run: yarn build

      # Step 6: Deploy the Docusaurus site to GitHub Pages
      - name: Deploy to GitHub Pages
        run: yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this token

      # Optional: Clear the cache if there are issues with caching
      - name: Clear Yarn cache (if needed)
        run: yarn cache clean
